"""
HighStudio — SQLAlchemy Model Base & Shared Enums

Defines the declarative base, common mixins, and all enum types
used across the artifact lifecycle.
"""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""

    pass


class TimestampMixin:
    """Adds created_at and updated_at columns to any model."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary key column."""

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )


# ── Enum Types ────────────────────────────────────────────────


class ProjectStatus(str, enum.Enum):
    """Overall project lifecycle status."""

    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class ArtifactType(str, enum.Enum):
    """Types of engineering artifacts generated by the system."""

    CONTEXT_ANALYSIS = "CONTEXT_ANALYSIS"
    FDD = "FDD"
    TDD = "TDD"
    SQL = "SQL"
    PKS = "PKS"
    PKB = "PKB"
    DEPLOYMENT = "DEPLOYMENT"


class GateStatus(str, enum.Enum):
    """Current gate status of an artifact within the workflow."""

    LOCKED = "LOCKED"
    GENERATING = "GENERATING"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    INVALIDATED = "INVALIDATED"


class VersionState(str, enum.Enum):
    """Lifecycle state of an individual artifact version."""

    DRAFT = "DRAFT"
    AI_VALIDATED = "AI_VALIDATED"
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    APPROVED = "APPROVED"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECTED = "REJECTED"
    INVALIDATED = "INVALIDATED"


class AuditAction(str, enum.Enum):
    """Actions recorded in the audit trail."""

    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    SUBMITTED_FOR_REVIEW = "SUBMITTED_FOR_REVIEW"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"
    INVALIDATED = "INVALIDATED"
    REGENERATED = "REGENERATED"


class ValidationCategory(str, enum.Enum):
    """Categories of automated validation checks."""

    SCHEMA = "SCHEMA"
    MAPPING = "MAPPING"
    SQL = "SQL"
    PLSQL = "PLSQL"
    DOCUMENT = "DOCUMENT"
    CROSS_ARTIFACT = "CROSS_ARTIFACT"


class ValidationStatus(str, enum.Enum):
    """Outcome of a validation run."""

    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"


class IdentityStatus(enum.StrEnum):
    """Lifecycle state for a federated identity subject."""

    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    DISABLED = "DISABLED"


class ClientStatus(enum.StrEnum):
    """Lifecycle state for a customer boundary."""

    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class MembershipStatus(enum.StrEnum):
    """Lifecycle state for a role assignment."""

    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class ClientRole(enum.StrEnum):
    """Roles evaluated within one client boundary."""

    CLIENT_ADMIN = "CLIENT_ADMIN"
    FUNCTIONAL_REVIEWER = "FUNCTIONAL_REVIEWER"
    TECHNICAL_REVIEWER = "TECHNICAL_REVIEWER"
    TESTER = "TESTER"
    CONSULTANT = "CONSULTANT"


class PlatformRole(enum.StrEnum):
    """Roles evaluated across client boundaries for platform administration."""

    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    ERP_CONFIGURATOR = "ERP_CONFIGURATOR"
    ERP_PUBLISHER = "ERP_PUBLISHER"
    AUDITOR = "AUDITOR"


class InstallationStatus(enum.StrEnum):
    """Lifecycle state for a client ERP installation record."""

    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    ARCHIVED = "ARCHIVED"


class EnvironmentType(enum.StrEnum):
    """Common environment categories; adapters may store additional metadata."""

    DEVELOPMENT = "DEVELOPMENT"
    SANDBOX = "SANDBOX"
    TEST = "TEST"
    UAT = "UAT"
    PRODUCTION = "PRODUCTION"


class EnvironmentStatus(enum.StrEnum):
    """Lifecycle state for an ERP execution environment."""

    ACTIVE = "ACTIVE"
    UNVERIFIED = "UNVERIFIED"
    SUSPENDED = "SUSPENDED"
    ARCHIVED = "ARCHIVED"
